spring.application.name=spring-ai
spring.ai.model.chat=vertexai
#spring.ai.model.chat=none


#cho phép b?n t? t?o nhi?u instance ChatClient m?t cách th? công
#spring.ai.chat.client.enabled=false


spring.ai.vertex.ai.gemini.project-id=spring-ai-2
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash
spring.ai.vertex.ai.gemini.chat.options.temperature=0.5


# C?u hình c? s? d? li?u
spring.datasource.url=jdbc:mysql://localhost:3306/chatbot
spring.datasource.username=root
spring.datasource.password=123456

# C?u hình kh?i t?o schema
spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.platform=mysql

# C?u hình Log ?? debug
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.jdbc=DEBUG


spring.ai.chat.memory.repository.jdbc.schema=classpath:schema-mysql.sql