spring.application.name=mcp
spring.main.web-application-type=none
spring.ai.mcp.client.stdio.servers-configuration=classpath:/mcp-servers-config.json
spring.ai.model.chat=vertexai
spring.ai.vertex.ai.gemini.project-id=spring-ai-2
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash
spring.ai.vertex.ai.gemini.chat.options.temperature=0.5